FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
SCRIPT_SED_ADDENDUM:append = " -e 's:@@FIT_DTB_IMAGE_NAME@@:${FIT_DTB_IMAGE_NAME}:'"
SCRIPT_SED_ADDENDUM:append = " -e 's:@@DEFAULT_FIT_IMAGE_PARTITION@@:${DEFAULT_FIT_IMAGE_PARTITION}:'"
