#@TYPE: Machine
#@NAME: genesyszu-3eg
#@DESCRIPTION: Machine support for Digilent Genesys ZU 3EG

#### Preamble
MACHINEOVERRIDES =. "${@['', 'genesyszu-3eg:']['genesyszu-3eg' !='${MACHINE}']}"
#### Regular settings follow

# Using the (deprecated) XSCT workflow because the 3eg/oob/master tree just
# has an .xsa in it, and not the appropriate stuff for SDT.
XILINX_WITH_ESW = "xsct"

# The external-hdf recipe really does not make this easy to use a HDF_URI
# that is _not_ a https:// or file://.
HDF_SRCREV = "29cd08a29305d354fbe98c18b698ccb171ae57fc"
HDF_URI = "git://github.com/Digilent/Genesys-ZU-OS.git;protocol=http;branch=3eg/oob/master;rev=${HDF_SRCREV}"
HDF_URI[sha256sum] = "${HDF_SRCREV}"
HDF_URI[S] = "${WORKDIR}/git/project-spec/hw-description"
HDF_NAME = "${S}/system.xsa"

ZYNQMP_SUBMODEL = "-eg"

require conf/machine/genesyszu.inc

### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' genesyszu-3eg']['genesyszu-3eg' != '${MACHINE}']}"
