#!/bin/sh

if [ -f /sys/firmware/devicetree/base/model ]; then
	read MODEL < /sys/firmware/devicetree/base/model
	echo "model is ${MODEL}, wanting linux,dummy-virt"
	if [ "${MODEL}" = "linux,dummy-virt" ]; then
		echo "PASS: model-check"
		exit 0
	else
		echo "FAIL: model-check"
		exit 1
	fi
else
	# TODO (AB#3968257): for non-devicetree QEMU platforms (e.g. x64) we should look at /sys/class/dmi/id
	echo "model check not implemented on non-devicetree platforms :("
	echo "FAIL: model-check"
	exit 1
fi
