BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-iba"
BBFILE_PATTERN_meta-iba = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-iba = "6"

LAYERDEPENDS_meta-iba = "core"
LAYERSERIES_COMPAT_meta-iba = "scarthgap"
