# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nile-test"
BBFILE_PATTERN_meta-nile-test = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nile-test = "7"

LAYERDEPENDS_meta-nile-test = "meta-nile"
LAYERSERIES_COMPAT_meta-nile-test = "scarthgap"
