[system]
compatible=kula
bootloader=uboot
bundle-formats=-plain
data-directory=/data/rauc/

[slot.rootfs.0]
device=/dev/mmcblk0p5
type=raw
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p6
type=raw
bootname=B

[slot.kernel.0]
device=/dev/mmcblk0p2
type=raw
parent=rootfs.0

[slot.kernel.1]
device=/dev/mmcblk0p3
type=raw
parent=rootfs.1

[keyring]
path=ca.cert.pem

[log.install-log]
filename=install.log
events=install
format=json
max-size=256K
max-files=2
